version: '3.7'

services:
  openweathermapmqtt:
    image: revenberg/openweathermapmqtt
    container_name: openweathermapmqtt
    environment:
      - apikey={{ openweathermap_apikey }}
      - WEATHER_COUNTRY=Surhuisterveen,NL
      - WEATHER_LANGUAGE=nl
      - MQTT_ADDRESS=192.168.2.80
      - MQTT_PORT=1883
      - MQTT_TOPIC=reading/weather
      - LOG_LEVEL=DEBUG
    restart: always
    depends_on:
      - mqttweather
    restart: always
    links:
      - mqttweather

  mqttweather:
    image: "eclipse-mosquitto:latest"
    container_name: mqttweather
    environment:
      - TZ=Europe/Amsterdam
      - "MQTT_BROKER_URL=mqtt://127.0.0.1"
    ports:
      - 1883:1883
      - 9001:9001
    user: "1000:1000"
    volumes:
      - /var/docker-compose/data/mqtt/config:/mosquitto/config
      - /var/docker-compose/data/mqtt/data:/mosquitto/data
      - /var/docker-compose/data/mqtt/log:/mosquitto/log
    restart: always
    network_mode: host
